name: libre_link_up_tray
description: LibreLinkUpTray application for monitoring glucose levels

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.3.7
  tray_manager:
    path: packages/tray_manager
  http: ^1.1.0
  shared_preferences: ^2.2.2
  crypto: ^3.0.3
  fluent_ui: ^4.12.0
  system_theme: ^3.1.2
  launch_at_startup: ^0.5.1
  package_info_plus: ^8.3.0
  local_notifier: ^0.1.6
  fluentui_icons: ^1.0.0
  dashed_path: ^1.0.1
  path_drawing: ^1.0.1
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4
  msix: ^3.16.9

flutter:
  uses-material-design: true
  assets:
    - assets/sensors/
    - assets/tray/
    - assets/tray/white/
    - assets/tray/black/
    - assets/tray/alert.ico
    - assets/tray/load.ico
    - assets/icon/icon.png
    - assets/data/testdata.json
    - assets/photos/libreview.png
    - assets/photos/liubquanti.png

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48

msix_config:
  display_name: LibreLinkUpTray
  publisher_display_name: liubquanti
  publisher: CN=F23B2EF8-5D90-4AF5-910B-1D05FBF4134B
  identity_name: liubquanti.LibreLinkUpTray
  msix_version: 0.0.1.0
  logo_path: assets/icon/icon.png
  capabilities: internetClient
  store: true